install:
	npm cache clean --force
	npm init -y
	npm i --save-dev @types/node
	npm install axios
	npm install --save-dev @types/axios 
	npm install -D vite @vitejs/plugin-react
	npm install

run:
	npx react-scripts start 
	npm start