iniciar-npm:
	npm init -y
	npm i --save-dev @types/node
	npm install --save-dev @types/axios
	npm install react-scripts@5.0.1 --save
	npm install
	npm audit fix --force

atualizar-npm:
	npm i --save-dev prisma@latest
	npm i @prisma/client@latest

executar-frontend:
	npm start